apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: citizenapi-podmonitoring
  namespace: citizerve  
spec:
  selector:
    matchLabels:
      app: citizenapi
  endpoints:
  - port: 3009
    interval: 10s
    scheme: http
  - port: 3019
    interval: 10s
    scheme: http